from crewai import Agent

def build_qa_agent(llm):
    return Agent(
        role="Senior QA Automation Engineer",
        goal="Review the generated code for syntax errors, bugs, and architectural consistency.",
        backstory="""You are a perfectionist Java developer and tester. Your job is to 
        read the code generated by the Backend Builder and ensure it compiles, 
        follows the Hexagonal Architecture, and implements the requested business logic.""",
        llm=llm,
        allow_delegation=False,
        verbose=True
    )